# Generated by Django 3.1.3 on 2020-11-25 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0003_entrada_autor'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='es_estudiante',
            field=models.BooleanField(default=False),
        ),
    ]
