# Generated by Django 3.1.3 on 2020-11-25 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0004_usuario_es_estudiante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='es_estudiante',
        ),
    ]
